name = "weather-mcp-with-auth"
compatibility_date = "2025-07-09"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 5342

[[d1_databases]]
binding = "DB"
database_name = "weather-mcp-with-auth-d1-database"
database_id = "9f837987-4004-43f9-bed4-1e7fc5552d25"
migrations_dir = "drizzle/migrations"

[vars]
BETTER_AUTH_URL = "https://weather.honc.dev"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"
